---
- name: Copy connection script
  copy:
    src: 'connect.py'
    dest: '{{ waku_peers_script_path }}'
    owner: 'admin'
    group: 'staff'
    mode: 0755

- name: Wait for RPC port
  wait_for:
    host: '{{ waku_peers_rpc_host }}'
    port: '{{ waku_peers_rpc_port }}'
    delay: 5

- name: Create timer for connecting peers
  include_role: name=systemd-timer
  vars:
    systemd_timer_name: '{{ waku_peers_timer_name }}'
    systemd_timer_description: '{{ waku_peers_timer_description }}'
    systemd_timer_documentation: 'https://github.com/status-im/infra-role-waku-peers'
    systemd_timer_consul_extra_tags: ['waku']
    systemd_timer_requires_extra: 'consul.service'
    systemd_timer_start_on_creation: true
    systemd_timer_enabled:         '{{ waku_peers_timer_enabled }}'
    systemd_timer_dynamic_user:    '{{ waku_peers_timer_dynamic_user }}'
    systemd_timer_frequency:       '{{ waku_peers_timer_frequency }}'
    systemd_timer_timeout_sec:     '{{ waku_peers_timer_timeout_sec }}'
    systemd_timer_restart:         '{{ waku_peers_timer_restart }}'
    systemd_timer_restart_delay:   '{{ waku_peers_timer_restart_delay }}'
    systemd_timer_restart_retries: '{{ waku_peers_timer_restart_retries }}'
    systemd_timer_script_path:     '{{ waku_peers_script_path }}'
    systemd_timer_script_args: |
      --rpc-host={{ waku_peers_rpc_host }} \
      --rpc-port={{ waku_peers_rpc_port }} \
      --rpc-timeout={{ waku_peers_rpc_timeout }} \
      --rpc-retries={{ waku_peers_rpc_retries }} \
      {% for service in waku_peers_consul_services %}
      --service='{{ service | to_json }}' \
      {% endfor %}
      --log-level={{ waku_peers_log_level }}

- name: Check for connected peers
  uri:
    url: 'http://{{ waku_peers_rpc_host }}:{{ waku_peers_rpc_port }}/'
    method: 'POST'
    body_format: 'json'
    return_content: true
    body: 
      method: 'get_waku_v2_admin_v1_peers'
      params: []
      jsonrpc: '2.0'
      id: 1
  register: nim_waku_rpc_peers

- name: 'Verify number of peers: {{ nim_waku_rpc_peers.json.result|length }}'
  assert:
    that: '{{ (nim_waku_rpc_peers.json.result|length) > 0 }}'
    fail_msg: 'Found connected peers!'
    quiet: true
